const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const authActions = {
    LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAIL, GET_CURRENT_USER
}