const GET_COMMON_DATA = 'GET_COMMON_DATA'
const REQUEST_COMMON_DATA = 'REQUEST_COMMON_DATA'
const RESET_STATE = 'RESET_STATE';
const FETCH_ALL_STEPCHART_LEVELS = 'FETCH_ALL_STEPCHART_LEVELS';
const FETCH_STANDARD_STEPCHART_LEVELS = 'FETCH_STANDARD_STEPCHART_LEVELS';
const FETCH_COOP_STEPCHART_LEVELS = 'FETCH_COOP_STEPCHART_LEVELS';

export const commonActions = {
    GET_COMMON_DATA , REQUEST_COMMON_DATA, RESET_STATE, 
    FETCH_ALL_STEPCHART_LEVELS, FETCH_STANDARD_STEPCHART_LEVELS, FETCH_COOP_STEPCHART_LEVELS
}