const GET_COMMON_DATA = 'GET_COMMON_DATA'
const REQUEST_COMMON_DATA = 'REQUEST_COMMON_DATA'
const RESET_STATE = 'RESET_STATE'

export const commonActions = {
    GET_COMMON_DATA , REQUEST_COMMON_DATA, RESET_STATE
}