const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
const FETCH_REQUESTS_PENDING = 'FETCH_REQUEST_PENDING';
const FETCH_REQUESTS_FAIL = 'FETCH_REQUEST_FAIL';
const RESET_STATE = 'RESET_STATE'

const SAVE_SEARCH_VALUE = 'SAVE_SEARCH_VALUE';

export const requestActions = {
    FETCH_REQUESTS_SUCCESS, FETCH_REQUESTS_PENDING, FETCH_REQUESTS_FAIL,
    SAVE_SEARCH_VALUE, RESET_STATE
}