const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
const FETCH_REQUESTS_PENDING = 'FETCH_REQUEST_PENDING';
const FETCH_REQUESTS_FAIL = 'FETCH_REQUEST_FAIL';
const RESET_STATE = 'RESET_STATE'

const SAVE_SEARCH_VALUE = 'SAVE_SEARCH_VALUE';

const DELETE_REQUEST_PENDING = 'DELETE_REQUEST_PENDING';
const DELETE_REQUEST_DONE = 'DELETE_REQUEST_FINISH';

export const requestActions = {
    FETCH_REQUESTS_SUCCESS, FETCH_REQUESTS_PENDING, FETCH_REQUESTS_FAIL,
    DELETE_REQUEST_PENDING, DELETE_REQUEST_DONE,
    SAVE_SEARCH_VALUE, RESET_STATE
}